#!/usr/bin/env ruby -w -U
# encoding: UTF-8
# (с) ANB Andrew Bizyaev Андрей Бизяев 

module ANB 

  class OSScript
    attr_reader :name, :file
    
    def initialize
      @file = File.new(@name, "w+:external")
      @file.chmod(0755) #make it executable
      add_header
    end #initialize
  
  
    def add_header
      add_comment "**********************************************************************"
      add_comment " Script generated by #{$0} "
      add_comment "**********************************************************************"
    end #def    

    def add_options
    end #def    
    
    def close
      @file.close
    end #def
    
  end #class
end #module